In [1]:
import numpy as np

#### zeros((n,m)) : is used to create a matrix of nXm dimension filled with zeros

In [3]:
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

#### .ones((n,m))

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### full((n,m), a): matrix of nXm dimension filled with a

In [10]:
np.full((5,5), 2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

#### np.arange

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

#### linearly spaced values
np.linspace


In [16]:
np.linspace(0,1,10)


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 3X3 array with random values between 0 and 1

In [19]:
np.random.rand(3,3)

array([[0.49488962, 0.61286017, 0.08484835],
       [0.16771262, 0.26904855, 0.81802966],
       [0.58136252, 0.28475857, 0.66109216]])

#### 3X3 array with random values between 0 and 1


In [22]:
np.random.rand(3,3)

array([[0.32001488, 0.32773074, 0.79170062],
       [0.7820274 , 0.127184  , 0.42343568],
       [0.78890246, 0.39830287, 0.72577211]])

#### 2X2 array with random integers between 1 and 10

In [25]:
np.random.randint(1,10, size=(2,2))


array([[4, 1],
       [7, 8]])

#### .eye() ientity matrix

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### .diag() used to fill specified diagonal values

In [31]:
np.diag([1,23,43])

array([[ 1,  0,  0],
       [ 0, 23,  0],
       [ 0,  0, 43]])

#### a.reshape()

In [34]:
a = np.array([1,2,3,4,5,56,67,78,89])

In [36]:
a.reshape((3,3))

array([[ 1,  2,  3],
       [ 4,  5, 56],
       [67, 78, 89]])

#### np.empty():- it gives the memory free of given space but that memory may have garbage vlue so to set it to zero we will need to use np.zero

In [39]:
b = np.empty(5)
print("1D empty array: " , b)

1D empty array:  [0.00000000e+000 1.21013991e-311 1.21013991e-311 1.21013991e-311
 5.81762784e+252]


In [41]:
# creating empty array with datatype
np.empty((3,3,2), dtype = 'int8')

array([[[-80,   3],
        [-19,  68],
        [ 58,   2]],

       [[  0,   0],
        [  0,   0],
        [  0,   0]],

       [[  0,   0],
        [  0,   0],
        [  2,   0]]], dtype=int8)

#### a.transpose() : use o transpose 'a' matrix

In [44]:
a = a.reshape((3,3))

In [46]:
print(a)
a.transpose()

[[ 1  2  3]
 [ 4  5 56]
 [67 78 89]]


array([[ 1,  4, 67],
       [ 2,  5, 78],
       [ 3, 56, 89]])

array([[92, 81, 74, 83, 51],
       [79,  0,  0,  0, 82],
       [68,  0,  0,  0, 84],
       [88,  0,  0,  0, 93],
       [56, 79, 82, 97, 82]])

In [48]:
a.ndim

2

In [50]:
a.size

9

In [52]:
a.shape

(3, 3)

In [54]:
a.nbytes

36

In [56]:
a.dtype


dtype('int32')

In [58]:
a_3d=np.array([[[1,2,3],[4,5,6]], [[6,7,9], [7,8,0]]], dtype = 'float32')
print(a_3d.ndim)

3


In [60]:
print(a_3d.shape)

(2, 2, 3)


In [62]:
print(a_3d.size)

12


In [64]:
a_3d.dtype

dtype('float32')

In [66]:
a_3d.itemsize

4

In [68]:
# a = np.array(['f','j', 'c'])
b = np.array([1.98, 2.98 , 3.09] ,)
c = np.array([True, False, True, False])
d = np.array([1,2,3])

In [70]:
# print(a.itemsize, b.itemsize, c.itemsize, d.itemsize)

In [72]:
print( b.itemsize, c.itemsize, d.itemsize)

8 1 4


In [74]:
# print(a.nbytes, b.nbytes, c.nbytes, d.nbytes)

In [76]:
print(b.nbytes, c.nbytes, d.nbytes)

24 4 12


In [78]:
print(b.dtype, c.dtype, d.dtype, sep = "--||--")

float64--||--bool--||--int32


In [80]:
# print(a.dtype, b.dtype, c.dtype, d.dtype, sep = "--||--")

## datatrasformation

In [83]:
a_3d=np.array([[[1,2,3],[4,5,6]], [[6,7,9], [7,8,0]]], dtype = 'float32')
print(a_3d.ndim)

3


In [85]:
a_3d[::-1]

array([[[6., 7., 9.],
        [7., 8., 0.]],

       [[1., 2., 3.],
        [4., 5., 6.]]], dtype=float32)

In [157]:
a_3d[1,0,0]

6.0

In [89]:
d

array([1, 2, 3])

In [91]:
d[2]

3

In [93]:
d[-2]

2

In [95]:
d[:2]

array([1, 2])

In [97]:
d[::-1]

array([3, 2, 1])

In [133]:
a= np.random.randint(1,21, (4,4))
a

array([[ 9,  5, 12,  5],
       [20, 20, 15,  8],
       [18,  5, 13,  7],
       [ 8, 15,  1, 18]])

In [147]:
a[1,3]


8

In [175]:
# toget the last coloum
a[::, 3::]

array([[ 5],
       [ 8],
       [ 7],
       [18]])

In [177]:
a[2::, 2::]

array([[13,  7],
       [ 1, 18]])

In [179]:
a[1:3 ,1:3]

array([[20, 15],
       [ 5, 13]])

In [181]:
a_3d

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[6., 7., 9.],
        [7., 8., 0.]]], dtype=float32)

In [209]:
# a_3d[0,1,0]
# a_3d[1,1,0]
a_3d[:, 1:, 0:2]

array([[[4., 5.]],

       [[7., 8.]]], dtype=float32)

In [189]:
a= np.random.randint(50,100, (5,5))
a

array([[92, 79, 68, 88, 56],
       [81, 98, 73, 91, 79],
       [74, 74, 59, 89, 82],
       [83, 51, 72, 63, 97],
       [51, 82, 84, 93, 82]])

In [191]:
a[1:4 , 1:4] = 0

In [193]:
a

array([[92, 79, 68, 88, 56],
       [81,  0,  0,  0, 79],
       [74,  0,  0,  0, 82],
       [83,  0,  0,  0, 97],
       [51, 82, 84, 93, 82]])

In [215]:
a_4d = np.random.randint(1, 100, (2,2,2,2))

In [217]:
a_4d

array([[[[83, 68],
         [ 1, 44]],

        [[81, 83],
         [32, 67]]],


       [[[22, 37],
         [97, 22]],

        [[17, 30],
         [51, 79]]]])

In [223]:
a_4d[1,0,0,0]

22

In [229]:
a_4d[:,:,:1,0:]

array([[[[83, 68]],

        [[81, 83]]],


       [[[22, 37]],

        [[17, 30]]]])

In [255]:
a_7 = np.random.randint(10, 100, (5,3))

In [265]:
a_7_t=a_7.T

In [263]:
a_7.mean()

62.06666666666667

In [267]:
a_7_t.mean()

62.06666666666667

In [251]:
a_8=np.random.randint(1,43,(2,3))
a_8

array([[ 5, 37, 27],
       [30, 11, 38]])

In [269]:
A=np.random.randint(2,8,(1,3))

In [271]:
A


array([[2, 2, 3]])

In [273]:
A.dtype

dtype('int32')

In [286]:
text = np.loadtxt('testt.csv', delimiter = ";") 

In [288]:
text

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [312]:
text1=np.genfromtxt("testt.csv", delimiter = ";")

In [306]:
text1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [319]:
a=np.arange(1,17)

In [321]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [329]:
b = np.sqrt(a)

In [331]:
b

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        ])

In [363]:
# np.savetxt("sqrt.csv",a,  delimiter = ',',header = "number")

In [365]:
# np.savetxt("sqrt.csv",b,  delimiter = ',',header = "sqrt")

In [373]:
combined_array=np.column_stack((a,b))

In [378]:
np.savetxt("sqrt.csv",combined_array,  delimiter = ',',header = "number ,sqrt" ,fmt= '%d, %.2f')

In [401]:
# assignment 10 matrix multiplication and transosition
a1 = np.random.randint(1,11,(4,2))
a2 = np.random.randint(1,11,(2,3))
a1

array([[8, 9],
       [6, 9],
       [2, 7],
       [1, 2]])

In [403]:
a1_a2 = np.matmul(a1,a2)

In [408]:
print(f"first matrix: \n{a1}\nsecond matrix: \n{a2}\ntransposed multiplied matrix: \n{a1_a2.T}")

first matrix: 
[[8 9]
 [6 9]
 [2 7]
 [1 2]]
second matrix: 
[[ 4  3  3]
 [ 9  3 10]]
transposed multiplied matrix: 
[[113 105  71  22]
 [ 51  45  27   9]
 [114 108  76  23]]
